# Generated by Django 5.0.1 on 2024-07-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderSuccess',
        ),
    ]
