# Generated by Django 5.0.1 on 2024-07-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_orderdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
