# Generated by Django 5.0.1 on 2024-07-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_order_product_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
