# Generated by Django 5.0.1 on 2024-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_news_author_alter_news_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
