# Generated by Django 5.0.1 on 2024-07-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_news_day_news_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='day',
        ),
        migrations.RemoveField(
            model_name='news',
            name='month',
        ),
    ]
