# Generated by Django 5.0.1 on 2024-07-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_news_day_remove_news_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
