# Generated by Django 5.0.1 on 2024-07-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_news_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
