# Generated by Django 5.0.1 on 2024-07-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_news_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='excerpt',
        ),
    ]
