# Generated by Django 5.0.1 on 2024-07-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_comment_created_at_alter_comment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
