# Generated by Django 5.0.1 on 2024-07-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
