# Generated by Django 5.0.1 on 2024-07-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_product_order_quantity_delete_createuserform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
